# Generated by Django 2.2.1 on 2019-05-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='average',
            field=models.DecimalField(decimal_places=1, default=6.0, max_digits=2),
        ),
    ]
