# Generated by Django 2.2.1 on 2019-05-15 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FilmModel', '0002_film_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
    ]
