# Generated by Django 2.2.1 on 2019-05-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmModel', '0003_remove_rating_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='casts',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='film',
            name='rating_people',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='stars',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='writers',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='aka',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='countries',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(default='119', max_length=20),
        ),
        migrations.AlterField(
            model_name='film',
            name='episodes',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='genres',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='languages',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='film',
            name='pubdate',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='film',
            name='season_count',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='title_en',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='title_zh',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.CharField(default='1998', max_length=20),
        ),
    ]
