# Generated by Django 2.2.1 on 2019-05-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmModel', '0005_auto_20190515_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='douban_site',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='lens_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='site',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='film',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
