# Generated by Django 2.2.1 on 2019-05-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FilmModel', '0006_auto_20190515_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(default='119', max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='title_en',
            field=models.CharField(default='title', max_length=150),
        ),
    ]
